# Generated by Django 6.0.6 on 2026-06-11 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('productos', '0002_producto_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('compra', 'Compra'), ('venta', 'Venta'), ('merma', 'Merma'), ('devolucion', 'Devolución')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='empresas.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-creado'],
            },
        ),
    ]
