# Generated by Django 6.0.6 on 2026-06-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
