# Generated by Django 6.0.6 on 2026-06-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_stock_descontado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='caja_registrada',
            field=models.BooleanField(default=False),
        ),
    ]
