# Generated by Django 6.0.6 on 2026-07-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedido_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
