# Generated by Django 6.0.6 on 2026-07-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_alter_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icono',
            field=models.CharField(blank=True, default='🍽️', max_length=4, null=True),
        ),
    ]
