# Generated by Django 6.0.6 on 2026-06-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_reservado',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
