# Generated by Django 6.0.6 on 2026-07-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='es_consumidor_final',
            field=models.BooleanField(default=False),
        ),
    ]
