# Generated by Django 6.0.6 on 2026-06-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
