# Generated by Django 6.0.6 on 2026-07-12 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.caja'),
        ),
    ]
