# Generated by Django 6.0.6 on 2026-07-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_movimientocaja_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='observaciones_cierre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='saldo_contado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
