# Generated by Django 6.0.6 on 2026-06-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='stock_ingresado',
            field=models.BooleanField(default=False),
        ),
    ]
