# Generated by Django 6.0.6 on 2026-07-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_stock_ingresado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='numero',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
